import { StyleSheet } from 'react-native';

export const accentColor = '#2f2a85';

export const globalStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f0f1f3' },
  container: { flex: 1, backgroundColor: '#f0f1f3' },
  containerPadded: { flex: 1, backgroundColor: '#f0f1f3', padding: 20 },
  centered: { justifyContent: 'center', alignItems: 'center' },
  info: { padding: 16, fontSize: 14, color: '#444' },
  infoCentered: { marginTop: 12, fontSize: 14, color: '#444' },
  list: { paddingBottom: 24 },
  titre: { fontSize: 18, fontWeight: '600', color: accentColor, marginBottom: 20 },
  bloc: {
    backgroundColor: '#fff',
    padding: 18,
    borderRadius: 10,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: { fontSize: 15, color: '#333' },
  chiffre: { fontSize: 22, fontWeight: 'bold', color: accentColor },
  card: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 14,
    borderRadius: 10,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  cardNom: { fontSize: 15, fontWeight: '600', color: '#222' },
  cardLigne2: { fontSize: 13, color: '#555', marginTop: 4 },
  cardLigne3: { fontSize: 12, color: '#666', marginTop: 2 },
  accueilScroll: { flex: 1, backgroundColor: '#f0f1f3' },
  accueilContent: { padding: 24, paddingBottom: 48, alignItems: 'center' },
  accueilLogo: { width: 100, height: 70, marginBottom: 20 },
  accueilTitre: { fontSize: 24, fontWeight: '600', color: accentColor, marginBottom: 4 },
  accueilAuteur: { fontSize: 14, color: '#666', marginBottom: 28 },
  accueilBouton: {
    alignSelf: 'stretch',
    backgroundColor: accentColor,
    borderRadius: 10,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  accueilTexteBouton: { color: '#fff', fontSize: 15 },
});
